# LWJGL Configs
# See https://www.lwjgl.org/customize
lwjgl_version = 3.3.4
joml_version = 1.10.7
steamworks4j_version = 1.9.0
lwjglNatives = natives-windows

# Google gson
# See https://mvnrepository.com/artifact/com.google.code.gson/gson
google_gson_version = 2.13.0

# Project
project_group = io.github.baole444
TCB_version = 1.0

# Jackson Yaml
# See https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml
jacksonYaml_version = 2.19.2

# SpaiR-imgui
# See https://central.sonatype.com/search?q=io.github.spair++imgui-java
imgui_version = 1.89.0