# LWJGL Configs
# See https://www.lwjgl.org/customize
lwjgl_version = 3.4.1
joml_version = 1.10.8
steamworks4j_version = 1.10.0
## Windows
lwjgl_window = natives-windows
imgui_window = natives-windows

## Linux
lwjgl_linux = natives-linux
imgui_linux = natives-linux

## MacOS
lwjgl_macos_arm64 = natives-macos-arm64
lwjgl_macos = natives-macos
imgui_macos = natives-macos

# Google gson
# See https://mvnrepository.com/artifact/com.google.code.gson/gson
google_gson_version = 2.13.2

# Project
project_group = io.github.baole444
TCB_version = 1.6

# Jackson Yaml
# See https://mvnrepository.com/artifact/tools.jackson.dataformat/jackson-dataformat-yaml
jacksonYaml_version = 3.1.1

# SpaiR-imgui
# See https://central.sonatype.com/search?q=io.github.spair++imgui-java
imgui_version = 1.92.0