package generator;

import io.github.classgraph.ClassGraph;
import io.github.classgraph.ClassInfo;
import io.github.classgraph.ScanResult;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Emit the API probe tool and force javac to actively complete the types of the API jar.
 * If there is a gap cause by missing type. this indicates the API is incomplete and likely not usable in practice.
 */
public final class CanaryGenerator {
    private CanaryGenerator() {}

    static void main(String[] args) throws IOException {
        if (args.length != 2) throw new IllegalArgumentException("Usage: CanaryGenerator <apiJarPath> <outputJavaPath>");
        String apiJarPath = args[0];
        Path outputPath = Path.of(args[1]);
        List<String> types = new ArrayList<>();
        ClassGraph classGraph = new ClassGraph().overrideClasspath(apiJarPath).enableAllInfo().enableExternalClasses();
        try (ScanResult scan = classGraph.scan()) {
            for (ClassInfo info : scan.getAllClasses()) {
                if (info.isExternalClass() || !info.isPublic() || info.isAnnotation()) continue;
                if (referenceable(info)) types.add(info.getName());
            }
        }
        types.sort(Comparator.naturalOrder());
        StringBuilder src = new StringBuilder();
        src.append("/*\n")
                .append("Generated by CanaryGenerator - do not edit.\n\n")
                .append("Force javac to complete each type against the built API and the provisioned flat jar, \n")
                .append("by declaring a variable of the type and call one of its member.\n")
                .append("A hole in the surface will fail the compilation, proving the API jar is usable in practice. or not.\n")
                .append("*/\n\n");
        src.append("package canary;\n\n");
        src.append("@SuppressWarnings({\"unchecked\", \"rawtypes\", \"deprecation\", \"removal\"})\n")
                .append("public final class APICanary {\n")
                .append("\tprivate APICanary() {}\n\n")
                .append("\tstatic void probe() {\n");
        for (int i = 0; i < types.size(); i++) {
            String ref = types.get(i).replace('$', '.');
            src.append("\t\t").append(String.format("%s v%d = null;%n", ref, i));
            src.append("\t\t").append(String.format("if (v%d != null) v%d.hashCode();%n", i, i));
        }
        src.append("\t}\n").append("}\n");
        Files.createDirectories(outputPath.getParent());
        Files.writeString(outputPath, src.toString(), StandardCharsets.UTF_8);
        System.out.printf("Canary probes %d public API types -> %s%n", types.size(), outputPath);
    }

    /**
     * Check if a nested type can be referenced or not. This requires it and every enclosing type to be public and named.
     * @param info the class to check
     * @return true if the inner class can be referenced
     */
    private static boolean referenceable(ClassInfo info) {
        if (info.getName().matches(".*\\$\\d.*")) return false;
        for (ClassInfo outer : info.getOuterClasses()) if (!outer.isPublic()) return false;
        return true;
    }
}
